### PR TITLE
Fix selectable lizard version

### PR DESCRIPTION
**Pull request by pascalzauberzeug**
Using `bind_value` on `version_select` leads to a recursion error.
I'm not quite sure yet what causes this, but using `bind_value_to` helps.

Additionally, 329ad6dfb3a1d5507ab1c1ec0af70675d302c7a2 sets the selection to the latest version when the list is updated.

```
rosys_1  | 2024-11-04 23:18:34.374 [ERROR] nicegui/app/app.py:122: maximum recursion depth exceeded
rosys_1  | Traceback (most recent call last):
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/events.py", line 430, in handle_event
rosys_1  |     result = cast(Callable[[EventT], Any], handler)(arguments)
rosys_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 40, in handle_change
rosys_1  |     self.set_value(self._event_args_to_value(e))
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 108, in set_value
rosys_1  |     self.value = value
rosys_1  |     ^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 153, in __set__
rosys_1  |     _propagate(owner, self.name)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 77, in _propagate
rosys_1  |     _propagate(target_obj, target_name, visited)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 76, in _propagate
rosys_1  |     _set_attribute(target_obj, target_name, target_value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 33, in _set_attribute
rosys_1  |     setattr(obj, name, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 153, in __set__
rosys_1  |     _propagate(owner, self.name)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 77, in _propagate
rosys_1  |     _propagate(target_obj, target_name, visited)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 76, in _propagate
rosys_1  |     _set_attribute(target_obj, target_name, target_value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 33, in _set_attribute
rosys_1  |     setattr(obj, name, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 153, in __set__
rosys_1  |     _propagate(owner, self.name)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 77, in _propagate
rosys_1  |     _propagate(target_obj, target_name, visited)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 76, in _propagate
rosys_1  |     _set_attribute(target_obj, target_name, target_value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 33, in _set_attribute
rosys_1  |     setattr(obj, name, value)
...
...
...
...
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 153, in __set__
rosys_1  |     _propagate(owner, self.name)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 77, in _propagate
rosys_1  |     _propagate(target_obj, target_name, visited)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 76, in _propagate
rosys_1  |     _set_attribute(target_obj, target_name, target_value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 33, in _set_attribute
rosys_1  |     setattr(obj, name, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 155, in __set__
rosys_1  |     self._change_handler(owner, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 23, in <lambda>
rosys_1  |     on_change=lambda sender, value: cast(Self, sender)._handle_value_change(value))  # pylint: disable=protected-access
rosys_1  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/validation_element.py", line 74, in _handle_value_change
rosys_1  |     super()._handle_value_change(value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 113, in _handle_value_change
rosys_1  |     self.update()
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/choice_element.py", line 37, in update
rosys_1  |     self._update_options()
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/choice_element.py", line 33, in _update_options
rosys_1  |     self.value = before_value if before_value in self._values else None
rosys_1  |     ^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 153, in __set__
rosys_1  |     _propagate(owner, self.name)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 77, in _propagate
rosys_1  |     _propagate(target_obj, target_name, visited)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 76, in _propagate
rosys_1  |     _set_attribute(target_obj, target_name, target_value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 33, in _set_attribute
rosys_1  |     setattr(obj, name, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/binding.py", line 155, in __set__
rosys_1  |     self._change_handler(owner, value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 23, in <lambda>
rosys_1  |     on_change=lambda sender, value: cast(Self, sender)._handle_value_change(value))  # pylint: disable=protected-access
rosys_1  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/validation_element.py", line 74, in _handle_value_change
rosys_1  |     super()._handle_value_change(value)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/mixins/value_element.py", line 113, in _handle_value_change
rosys_1  |     self.update()
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/elements/choice_element.py", line 38, in update
rosys_1  |     super().update()
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/element.py", line 388, in update
rosys_1  |     self.client.outbox.enqueue_update(self)
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/outbox.py", line 41, in enqueue_update
rosys_1  |     self._set_enqueue_event()
rosys_1  |   File "/usr/local/lib/python3.12/site-packages/nicegui/outbox.py", line 35, in _set_enqueue_event
rosys_1  |     self._enqueue_event.set()
rosys_1  | RecursionError: maximum recursion depth exceeded
```

### CODE REVIEW

**Comment by pascalzauberzeug** [comment]
I think there is still an issue, I will check again

**Comment by pascalzauberzeug** [comment]
I just tested it on F15, works!
@falkoschindler Is there maybe a bug in nicegui that leads to the recursion, because I'm pretty sure it worked, when I first implemented it here https://github.com/zauberzeug/rosys/pull/194

**Comment by falkoschindler** [comment]
When reviewing the change with @pascalzauberzeug, we didn't quite understand the recursion error. Before merging into main, we want to reproduce the problem once again and analyze the root cause.

**Comment by pascalzauberzeug** [comment]
Sadly, we couldn't reproduce the error, but decided that reworking the version selection makes sense anyway.

**Review by falkoschindler — APPROVED** [review]

**Pull request merged**
