### PR TITLE
Fix Calibration Serialization

### PR DESCRIPTION
**Pull request by NiklasNeugebauer**
make model field a string instead of CameraModel to support direct json serialization

### CODE REVIEW

**Comment by falkoschindler** [comment]
I wonder if we need the `CameraModel` at all. Can't we simply use a `Literal` string? It might feel a little more fragile, but using static type checkers will prevent us from typos.

**Comment by NiklasNeugebauer** [comment]
I mostly like the ability to write CameraModel.PINHOLE

**Comment by NiklasNeugebauer** [comment]
I ended up using @pascalzauberzeug 's suggestion of deriving from `str` and `Enum`.
Also removed all `to_dict` functions since they should be unnecessary now.

**Review by pascalzauberzeug — COMMENTED** [review]
Looks good, we will test it on a robot later today

**Comment by codingpaula** [comment]
How did the test go? Can we merge this?

**Comment by pascalzauberzeug** [comment]
@codingpaula We didn't get to it yet, but I will do it now and merge when I'm done

**Comment by pascalzauberzeug** [comment]
Seems to work! I will merge it

```
{
    "cameras": {
        "32e4-9230-platform-3610000.xhci-usb-0:2.1:1.0": {
            "id": "32e4-9230-platform-3610000.xhci-usb-0:2.1:1.0",
            "name": "32e4-9230-platform-3610000.xhci-usb-0:2.1:1.0",
            "connect_after_init": true,
            "streaming": true,
            "focal_length": 1830,
            "calibration": {
                "intrinsics": {
                    "model": "pinhole",
                    "matrix": [
                        [
                            1433.6721216716353,
                            0.0,
                            347.7277694468386
                        ],
                        [
                            0.0,
                            1370.2101675446997,
                            239.1060666171041
                        ],
                        [
                            0.0,
                            0.0,
                            1.0
                        ]
                    ],
                    "distortion": [
                        -0.01557127473024067,
                        -56.25674323172758,
                        0.23577466596211383,
                        0.011342764817018949,
                        421.8140030391272
                    ],
                    "xi": 0.0,
                    "rotation": {
                        "R": [
                            [
                                1.0,
                                0.0,
                                0.0
                            ],
                            [
                                0.0,
                                1.0,
                                0.0
                            ],
                            [
                                0.0,
                                0.0,
                                1.0
                            ]
                        ]
                    },
                    "size": {
                        "width": 720,
                        "height": 560
                    }
                },
                "extrinsics": {
                    "rotation": {
                        "R": [
                            [
                                -0.005087957942356058,
                                0.9070537937934018,
                                -0.42098399951657745
                            ],
                            [
                                0.9967070483093687,
                                -0.02946986293924958,
                                -0.075541955420596
                            ],
                            [
                                -0.08092695802019419,
                                -0.419982073835704,
                                -0.9039169680464345
                            ]
                        ]
                    },
                    "translation": [
                        0.5757624106417404,
                        0.0740620510871811,
                        1.1604844656286453
                    ]
                }
            },
            "auto_exposure": true,
            "exposure": false,
            "width": 1280,
            "height": 720,
            "fps": 9
        }
    }
}
```

**Pull request merged**
